#!/bin/bash

# Init .env
set -a; source "$(dirname "$0")/.env"; set +a

az network vnet subnet create \
  -n $SUBNET_NAME \
  --vnet-name $VNET_NAME \
   --resource-group $RG \
  --address-prefixes $vnetSubnetPrefix \
  